server:
  port: 8080

logging:
  level:
    org.hibernate.type.descriptor.sql: trace


spring:
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100

    hibernate:
      ddl-auto: create

